### ISSUE TITLE
VMLogs data source is not working from grafana in mothership cluster

### ISSUE THREAD

**Issue by gmlexx** [Mirantis/motel#2]
Grafana is unable to load the datasource details on mothership cluster, not error in log or UI, but it works from the regional cluster.

<img width="818" alt="Image" src="https://github.com/user-attachments/assets/64542ef0-e452-4d21-9137-d1f12013e1b3" />

**Comment by pbasov** [comment]
https://github.com/Mirantis/motel/commit/58057e578e6fb39a5fcaf27cd95d3d37549f72fd

Fixed
